name: 'SlackFeedBot'
author: 'selfagency'
description: 'Push RSS feed updates to Slack via GitHub Actions'
branding:
  icon: 'rss'
  color: 'orange'
inputs:
  rss:
    description: 'RSS Feed URL'
    required: true
  slack_webhook:
    description: 'Slack Webhook URL'
    required: true
  interval:
    description: 'Minutes between workflow runs'
    required: true
  unfurl:
    description: 'Unfurl links'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
