name: 'FeedBot'
description: 'Push RSS feed updates to Slack'
inputs:
  rss:
    description: 'RSS Feed URLs'
    type: 'array'
    required: true
  slack_webhook:
    description: 'Slack Webhook URL'
    type: 'string'
    required: true
  interval:
    description: 'Minutes between workflow runs'
    type: 'number'
    required: true
  unfurl:
    description: 'Unfurl links'
    type: 'boolean'
    required: false
runs:
  using: 'node16'
  main: 'action.js'
