name: 'FeedBot'
description: 'Push RSS feed updates to Slack via GitHub Actions'
inputs:
  rss:
    description: 'RSS Feed URL'
    required: true
  slack_webhook:
    description: 'Slack Webhook URL'
    required: true
  interval:
    description: 'Minutes between workflow runs'
    required: true
  unfurl:
    description: 'Unfurl links'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RSS: '${{ inputs.rss }}'
    SLACK_WEBHOOK: '${{ inputs.slack_webhook }}'
    INTERVAL: '${{ inputs.interval }}'
    UNFURL: '${{ inputs.unfurl }}'
