name: 'SlackFeedBot'
author: 'selfagency'
description: 'Push RSS feed updates to Slack via GitHub Actions'
branding:
  icon: 'rss'
  color: 'orange'
inputs:
  rss:
    description: 'RSS feed URL'
    required: true
  feed_name:
    description: 'Feed name'
    required: false
  feed_image:
    description: 'Feed image URL'
    required: false
  slack_webhook:
    description: 'Slack webhook URL'
    required: true
  cache_dir:
    description: 'Cache folder'
    required: true
  interval:
    description: 'Minutes between workflow runs'
    required: false
  show_date:
    description: 'Show date in output'
    required: false
  show_link:
    description: 'Show link in output'
    required: false
  show_description:
    description: 'Show description in output'
    required: false
  unfurl:
    description: 'Unfurl links'
    required: false
  title_filter_include:
    description: 'Filter RSS feed by title (includes)'
    required: false
  title_filter_exclude:
    description: 'Filter RSS feed by title (excludes)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.cjs'
