name: FeedBot
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  rss-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v2
        with:
          path: ./slackfeedbot-cache
          key: slackfeedbot-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: slackfeedbot-cache-
      - name: NYT
        uses: 'selfagency/slackfeedbot@dev'
        with:
          rss: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: ./slackfeedbot-cache
          unfurl: false
      - name: LAT
        uses: 'selfagency/slackfeedbot@dev'
        with:
          rss: 'https://www.latimes.com/rss2.0.xml'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: ./slackfeedbot-cache
          unfurl: false
      - name: WaPo
        uses: 'selfagency/slackfeedbot@dev'
        with:
          rss: 'https://feeds.washingtonpost.com/rss/homepage'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: ./slackfeedbot-cache
          unfurl: false