name: FeedBot
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  rss-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v2
        with:
          path: ./slackfeedbot-cache
          key: feed-cache-i-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-i-
      - name: Apple Releases
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://developer.apple.com/news/releases/rss/releases.rss'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
          title_filter_exclude: 'beta,iPadOS,tvOS'
        continue-on-error: true
      - name: Infosec News Actively Exploited
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/actively-exploited/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News Apple
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/apple/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News AWS
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/aws/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News Infrastructure as Code
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/iac/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News Azure AD
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/azure-ad/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News MacOS
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/macos/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News Terraform
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/terraform/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News API security
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/api-security/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
      - name: Infosec News Identity and Access Management
        uses: 'HarryMooreRaidiam/slackfeedbot@main'
        with:
          rss: 'https://allinfosecnews.com/topic/iam/feed/'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          cache_dir: './slackfeedbot-cache'
        continue-on-error: true
